core_app/urls.py
from django.urls import path

from .views import views
from .views.auth_views import LoginView, RegisterView, ResetPasswordView, logout_view
from .views.discovery_view import Discovery
from .views.review_view import ReviewView
from .views.cart_view import CartView
from .views.checkout_view import DetailsView, ShippingView, PaymentView, PaymentConfirmedView
from .views.profile_view import InfoChangeView, BillingPayments, Settings, TransactionsHistory


app_name = 'core_app'

urlpatterns = [
    path('', views.index, name='index'),
    path('discovery/', Discovery.as_view(), name='discovery'),
    path('item/<int:item_id>', Discovery.as_view(), name='detailed_item'),
    path('cart/', CartView.as_view(), name='cart'),
    # Auth Views
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', logout_view, name='logout'),
    path('review/', ReviewView.as_view(), name='review'),
    path('about/', views.about, name='about'),
    path('registration/', RegisterView.as_view(), name='registration'),
    path('reset-password/', ResetPasswordView.as_view(), name='reset_password'),
    # Settings Views
    path('my-profile/', InfoChangeView.as_view(), name='my_profile'),
    path('my-profile/details', InfoChangeView.as_view(), name='details'),
    path('my-profile/transactions', TransactionsHistory.as_view(), name='transactions'),
    path('my-profile/billing', BillingPayments.as_view(), name='billing'),
    path('my-profile/settings', Settings.as_view(), name='settings'),
    # Checkout Views
    path('checkout/details', DetailsView.as_view(), name='checkout_details'),
    path('checkout/shipping', ShippingView.as_view(), name='checkout_shipping'),
    path('checkout/payment', PaymentView.as_view(), name='checkout_payment'),
    path('checkout/payment/confirmation/<int:order_id>/', PaymentConfirmedView.as_view(), name='payment_confirmed'),
]

webshop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core_app.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core_app/views/auth_views.py
from django.shortcuts import render, redirect
from django.contrib.auth import logout
from django.contrib.auth.views import LoginView
from django.http import HttpResponseRedirect
from ..forms import RegistrationForm, ResetPasswordForm
from django.contrib import messages
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.views import View

class LoginView(LoginView):
    template_name = 'core_app/auth/login.html'
    success_url = '/'

class RegisterView(View):
    def get(self, request):
        form = RegistrationForm()
        return render(request, 'core_app/auth/registration.html', {'form': form}) 

    def post(self, request):
        form = RegistrationForm(request.POST)
        print(form)
        if form.is_valid():
            user = form.save(commit=False)
            print(user)
            user.set_password(form.cleaned_data['password'])
            user.save()
            return redirect('core_app:login')
        return render(request, 'core_app/auth/registration.html', {'form': form})

class ResetPasswordView(View):
    def get(self, request):
        form = ResetPasswordForm()
        return render(request, "core_app/auth/reset_password.html", {"form": form})

    def post(self, request):
        form = ResetPasswordForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data["username"]
            email = form.cleaned_data["email"]
            new_password = form.cleaned_data["new_password"]

            try:
                user = User.objects.get(username=username, email=email)
                user.set_password(new_password)  
                user.save()  
                messages.success(request, "Password reset successfully!")
                return redirect("core_app:login")  
            except User.DoesNotExist:
                messages.error(request, "No user found with the given username and email!")
                return redirect("core_app:reset_password")
        return render(request, "core_app/auth/reset_password.html", {"form": form})

@login_required
def logout_view(request):
    logout(request)
    return HttpResponseRedirect('/')

core_app/views/cart_view.py
from django.shortcuts import render, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.views import View
from ..models import Candle
from django.http import HttpResponseRedirect
from django.contrib import messages

class CartView(View):
    def get(self, request):
        cart = request.session.get('cart', {})

        subTotal = 0
        items = []
        for id, quantity in cart.items():
            item = get_object_or_404(Candle, id=id)

            if item.in_stock == 0:
                # Skip items if out of stock
                continue

            if quantity > item.in_stock:
                # Change quantity to match the available stock
                quantity = item.in_stock
                cart[id] = quantity

            items.append({'item': item, 'quantity': quantity})
            subTotal += item.price * quantity
        
        # Update the session cart with new quantity values
        request.session['cart'] = cart

        return render(request, 'core_app/cart.html', {'items': items, 'cart_count': sum(cart.values()), 'subTotal': subTotal})
    
    def post(self, request):
        method = self.request.POST.get('method', '').lower()
        item_id = self.request.POST.get('item_id', '').lower()
        if method == 'delete':
            return self.delete(request, item_id)
        
        quantity  = int(request.POST.get('quantity'))
        cart = request.session.get('cart', {})
        cart[item_id] = quantity

        request.session['cart'] = cart 
        return HttpResponseRedirect(request.META.get('HTTP_REFERER'))
    
    def delete(self, request, item_id):
        cart = request.session.get('cart', {})
        if cart and cart[item_id]:
            cart.pop(item_id)
            request.session['cart'] = cart 

        return HttpResponseRedirect(request.META.get('HTTP_REFERER'))

core_app/views/checkout_view.py
from django.views import View
from django.shortcuts import render, get_object_or_404, redirect, reverse
from ..models import Candle, Order, OrderItem, User
from django.http import HttpResponseRedirect
from django.contrib import messages
from datetime import datetime

class CheckoutUtils:
    @staticmethod
    def process_cart(request):
        cart = request.session.get('cart', {})
        subTotal = 0
        items = []

        for id, quantity in cart.items():
            item = get_object_or_404(Candle, id=id)

            if item.in_stock == 0 or quantity > item.in_stock:
                messages.warning(
                    request,
                    f"Unfortunately, the item '{item.title}' is no longer available in the quantity you requested. "
                    f"We currently have {item.in_stock} left in stock. Please update your cart to proceed."
                )
                return None, None

            items.append({'item': item, 'quantity': quantity})
            subTotal += item.price * quantity
        
        return items, subTotal

class DetailsView(View):
    def get(self, request):
        items, subTotal = CheckoutUtils.process_cart(request)
        if items is None:
            return redirect('/cart')

        return render(request, 'core_app/checkout/details.html', {'items': items, 'subTotal': subTotal})

    def post(self, request):
        allowed_keys = [
            'email', 'newsletter', 'first_name', 'last_name', 'address', 
            'shipping_note', 'city', 'postal_code', 'province', 'country', 'save_info'
        ]
        details = {key: request.POST.get(key) for key in allowed_keys}
        checkout = request.session.get('checkout', {})
        checkout['details'] = details
        request.session['checkout'] = checkout

        return HttpResponseRedirect(reverse('core_app:checkout_shipping'))

class ShippingView(View):
    def get(self, request):
        items, subTotal = CheckoutUtils.process_cart(request)
        if items is None:
            return redirect('/cart')

        checkout = request.session.get('checkout', {})
        contact = checkout['details']['email']
        ship_to = f"{checkout['details']['address']}, {checkout['details']['postal_code']}, {checkout['details']['province']}, {checkout['details']['country']}" 

        return render(request, 'core_app/checkout/shipping.html', {'items': items, 'subTotal': subTotal, 'contact': contact, 'ship_to': ship_to})
    
    def post(self, request):
        allowed_keys = ['contact', 'ship_to', 'standard_shipping']
        shipping = {key: request.POST.get(key) for key in allowed_keys}

        checkout = request.session.get('checkout', {})
        checkout['shipping'] = {
            **shipping,
            "cost": 0
        }
        request.session['checkout'] = checkout

        return HttpResponseRedirect(reverse('core_app:checkout_payment'))
    
class PaymentView(View):
    def get(self, request):
        items, subTotal = CheckoutUtils.process_cart(request)

        if items is None:
            return redirect('/cart')

        checkout = request.session.get('checkout', {})
        shipping_cost = checkout['shipping']['cost']

        total = subTotal + shipping_cost

        return render(request, 'core_app/checkout/payment.html', {'items': items, 'subTotal': subTotal, 'shipping': shipping_cost, 'total': total  })
    
    def post(self, request):
        allowed_keys = [
            'card_number', 'holder_name', 'expiration_date', 
            'cvv', 'vat_number', 'pec'
        ]

        payment_details = {key: request.POST.get(key) for key in allowed_keys}

        # check payment details
        payment_success = True

        if not payment_success:
            messages.warning(
                request,
                f"Unfortunately, the item payment failed. "
            )
            return redirect('/cart')
        

        checkout = request.session.get('checkout', {})

        cart = request.session.get('cart', {})
        subTotal = 0
        items = []

        for id, quantity in cart.items():
            item = get_object_or_404(Candle, id=id)

            if item.in_stock == 0 or quantity > item.in_stock:
                messages.warning(
                    request,
                    f"Unfortunately, the item '{item.title}' is no longer available in the quantity you requested. "
                    f"We currently have {item.in_stock} left in stock. Please update your cart to proceed."
                )
                return redirect('/cart')
            
            items.append({'item': item, 'quantity': quantity})
            subTotal += item.price * quantity

            item.in_stock -= quantity
            item.save()
        
        checkout = request.session.get('checkout', {})

        user = {}
        if request.user.is_authenticated:
            user = request.user
        else:
            details = checkout.get('details', {})
            user = User.objects.filter(email=details.get('email')).first()

            # Create a temporary user with a random password (guest user case)
            if not user:
                user = User.objects.create_user(
                    username=details.get('email', 'guest_user'),
                    email=details.get('email', ''),
                    password=User.objects.make_random_password(),
                    first_name=details.get('first_name', ''),
                    last_name=details.get('last_name', ''),
                )

        order = Order.objects.create(
            user=user,
            created_at=datetime.now()
        )

        for item in items:
            OrderItem.objects.create(
                order=order,
                item=item['item'],
                quantity=item['quantity']
            )

        return HttpResponseRedirect(reverse('core_app:payment_confirmed', args=[order.id]))

class PaymentConfirmedView(View):
    def get(self, request, order_id=None):
        items, subTotal = CheckoutUtils.process_cart(request)

        if items is None:
            return redirect('/cart')

        checkout = request.session.get('checkout', {})
        shipping_cost = checkout['shipping']['cost']

        total = subTotal + shipping_cost
        request.session['cart'] = {}
        request.session['checkout'] = {}
        return render(request, 'core_app/checkout/payment_confirmation.html', {'items': items, 'subTotal': subTotal, 'shipping': 'Free Shipping', 'paid': total, 'order_id': order_id})

core_app/views/discovery_view.py
from django.views import View
from ..models import Candle
from django.shortcuts import render, get_object_or_404, reverse
from django.http import HttpResponseRedirect
from django.db.models import Q


class Discovery(View):
    def get(self, request, item_id=None):
        cart = request.session.get('cart', {})
        cart_count = sum(cart.values())
    
        if item_id:
            item = get_object_or_404(Candle, id=item_id)
            quantity = cart.get(str(item_id))
            return render(request, 'core_app/discovery/detailed_item.html', {'cart_count': cart_count, 'item': item, 'quantity': quantity})
        
        category = request.GET.get('category', None)
        search_query = request.GET.get('search',None)

        items = []
        if category and search_query:
            items = Candle.objects.filter(
                Q(category=category) & (Q(title__icontains=search_query) | Q(description__icontains=search_query))
            )
        elif category:
            items = Candle.objects.filter(category=category)
        elif search_query:
            items = Candle.objects.filter(
                Q(title__icontains=search_query) | Q(description__icontains=search_query)
            )
        else:
            items = Candle.objects.all()
        
        return render(request, 'core_app/discovery/discovery.html', {'cart_count': cart_count, 'items': items, 'curr_category': category, 'categories': Candle.CATEGORY_CHOICES})


    def post(self, request): 
        item_id  = request.POST.get('product')
        new_quantity  = int(request.POST.get('quantity'))

        if not item_id or new_quantity < 0:
            return HttpResponseRedirect(request.META.get('HTTP_REFERER'))

        cart = request.session.get('cart', {})

        item = get_object_or_404(Candle, id=item_id)

        if item.in_stock < 0:
            return HttpResponseRedirect(request.META.get('HTTP_REFERER'))
        
        if new_quantity == 0:
            cart.pop(item_id, None)
        else:
            if new_quantity <= item.in_stock:
                cart[item_id] = new_quantity
            else:
                cart[item_id] = item.in_stock

        request.session['cart'] = cart 

        url = reverse('core_app:discovery')
        if item_id:
            url = f'{url}#{item_id}'

        return HttpResponseRedirect(url)

core_app/views/profile_view.py
from django.shortcuts import render, redirect
from ..forms import ChangeUserInfo
from django.contrib import messages
from django.views import View
from ..models import OrderItem


class InfoChangeView(View):
    def get(self, request):
        return render(request, 'core_app/my_profile/personal_details.html', {'user': request.user})
    
    def post(self, request):
        form = ChangeUserInfo(request.POST, instance=request.user)
        if form.is_valid():
            form.save()
            messages.success(request, "Your information has been updated.")
            return redirect('core_app:details')
        return render(request, 'core_app/my_profile/personal_details.html', {'user': request.user})


class BillingPayments(View):
    def get(self, request):
        return render(request, 'core_app/my_profile/billing.html')
    

class Settings(View):
    def get(self, request):
        return render(request, 'core_app/my_profile/settings.html')
    

class TransactionsHistory(View):
    def get(self, request):
        order_items = OrderItem.objects.filter(order__user=request.user)

        return render(request, 'core_app/my_profile/transactions.html', {
            'details' : order_items,
            "order_length" : len(order_items)
            })

core_app/views/review_view.py
from django.shortcuts import render
from django.contrib.auth import login, logout
from django.http import HttpResponse, HttpResponseRedirect
from ..models import Review
from django.contrib.auth.decorators import login_required
from django.views import View
from django.contrib.auth.mixins import LoginRequiredMixin


class ReviewView(LoginRequiredMixin, View):
    def get(self, request):
        return render(request, 'core_app/review.html', {'user' : request.user})
    
    def post(self, request):
        rating = request.POST.get('rating')
        review = request.POST.get('review')
        if rating:
            review_data = Review.objects.create(
                user=request.user,
                review=review,
                rating=rating
            )
            review_data.save()

            logout(request)
            return HttpResponseRedirect('/')
        else:
            logout(request)
            return HttpResponse('Invalid submission.', status=400)

templates/core_app/checkout/base.html
{% load static %}

<html>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="icon" href="{% static 'images/favicon.png' %}" type="image/png">
    <title>Candles</title>
    <!-- CSS -->
    <link rel="stylesheet" href="{% static 'css/base.css' %}">
    <link rel="stylesheet" href="{% static 'css/checkout.css' %}">
    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
        crossorigin="anonymous"></script>

    <!-- Google Fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link
        href="https://fonts.googleapis.com/css2?family=Merriweather:ital,wght@0,300;0,400;0,700;0,900;1,300;1,400;1,700;1,900&family=Roboto+Condensed:ital,wght@0,100..900;1,100..900&family=Stick+No+Bills:wght@200..800&display=swap"
        rel="stylesheet">
    <link
        href="https://fonts.googleapis.com/css2?family=Merriweather:ital,wght@0,300;0,400;0,700;0,900;1,300;1,400;1,700;1,900&family=Roboto+Condensed:ital,wght@0,100..900;1,100..900&family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;0,900;1,100;1,300;1,400;1,500;1,700;1,900&family=Stick+No+Bills:wght@200..800&display=swap"
        rel="stylesheet">
    <link rel="stylesheet"
        href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@24,400,0,0&icon_names=credit_card" />
</head>

<body>
    <div class="bg-white d-flex col">
        <div class="col">
            <nav>
                <h1 class="stick-no-bills-font fw-bold pt-4 px-4" ><a class="navbar-brand stick-no-bills-font fs-1 fw-normal" href="{% url 'core_app:index' %}">Candles</a></h1>

            </nav>
            <div class="px-5 align-items-center roboto-font">
                {% block body_block %}
                {% endblock %}
            </div>
        </div>

        {% include 'core_app/checkout/include/summary.html' %}

    </div>
</body>

</html>

templates/core_app/checkout/checkout_base.html
{% load static %}

<html>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="icon" href="{% static 'images/favicon.png' %}" type="image/png">
    <title>Candles</title>
    <!-- CSS -->
    <link rel="stylesheet" href="{% static 'css/base.css' %}">
    <link rel="stylesheet" href="{% static 'css/checkout.css' %}">
    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
        crossorigin="anonymous"></script>

    <!-- Google Fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link
        href="https://fonts.googleapis.com/css2?family=Merriweather:ital,wght@0,300;0,400;0,700;0,900;1,300;1,400;1,700;1,900&family=Roboto+Condensed:ital,wght@0,100..900;1,100..900&family=Stick+No+Bills:wght@200..800&display=swap"
        rel="stylesheet">
    <link
        href="https://fonts.googleapis.com/css2?family=Merriweather:ital,wght@0,300;0,400;0,700;0,900;1,300;1,400;1,700;1,900&family=Roboto+Condensed:ital,wght@0,100..900;1,100..900&family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;0,900;1,100;1,300;1,400;1,500;1,700;1,900&family=Stick+No+Bills:wght@200..800&display=swap"
        rel="stylesheet">
</head>

<body>
    <div class="d-flex col py-3 px-5">

        <div class="col">
            <nav>
                <h1 class="stick-no-bills-font fw-bold">Candles</h3>
            </nav>
            <div class="ml-2">
                {% block body_block %}
                {% endblock %}
            </div>
        </div>

        <div class="col overflow-auto" style="background-color: #e8e8e8; padding: 4%; max-height: 90vh;">

            {% for item in items %}
            <div class="d-flex align-items-start mb-5">
            <img src="{{ item.item.image.url }}" alt="{{ items.title }}" class="img-thumbnail" style="width: 80px; height: 80px; object-fit: cover;">
            <div class="ms-3">
                <h4 class="mb-4 mt-0 fs-5">{{ item.item.title }}</h4>
                <h4 class="mt-2 text-success fs-6">$ {{ item.item.price }}</h4>
            </div>
            </div>
            {% endfor %}
          
            <hr>
          
            <div class="mb-4 d-flex justify-content-between">
              <span>Subtotal</span>
              <span>${{ subTotal }}</span>
            </div>
            <div class="mb-5 d-flex justify-content-between">
              <span>Shipping</span>
              <span>Calculated at next step</span>
            </div>

            <hr>
          
            <div class="d-flex justify-content-between mt-5">
              <span>Total</span>
              <span class="fs-2"><b>${{ total }}</b></span>
            </div>
          </div>

    </div>
</body>

</html>

templates/core_app/checkout/details.html
{% extends "core_app/checkout/base.html" %}
{% load static %}
{% block body_block %}


<div>
  <ul class="steps">
    <li class="completed">Cart</li>
    <li>></li>
    <li class="active">Details</li>
    <li>></li>
    <li class="upcoming">Shipping</li>
    <li>></li>
    <li class="upcoming">Payments</li>
  </ul>


  <div class="section-heading">
    <h5>Contact</h5>
    <span><i>Do you have an account?</i><span> <a href="{% url 'core_app:login' %}" class="text-primary">Login</a>
  </div>

  <form method="post" action="{% url 'core_app:checkout_details' %}">
    {% csrf_token %}
    <div class="mb-3">
      <input type="email" name="email" class="form-control" placeholder="Email or Phone Number">
    </div>
    <div class="form-check mb-4">
      <input type="hidden" name="newsletter" value="off">
      <input class="form-check-input" name="newsletter" type="checkbox" id="newsletter">
      <label class="form-check-label" for="newsletter">Add me to Candles newsletter.</label>
    </div>

    <div class="section-heading">
      <h5>Shipping Address</h5>
    </div>

    <div class="row mb-3">
      <div class="col">
        <input type="text" name="first_name" class="form-control" placeholder="First Name" required>
      </div>
      <div class="col">
        <input type="text" name="last_name" class="form-control" placeholder="Last Name" required>
      </div>
    </div>

    <div class="mb-3">
      <input type="text" name="address" class="form-control" placeholder="Address and Number" required>
    </div>

    <div class="mb-3">
      <input type="text" name="shipping_note" class="form-control" placeholder="Shipping Note (Optional)">
    </div>

    <div class="row mb-3">
      <div class="col">
        <input type="text" name="city" class="form-control" placeholder="City" required>
      </div>
      <div class="col">
        <input type="text" name="postal_code" class="form-control" placeholder="Postal Code" required>
      </div>
      <div class="col">
        <input type="text" name="province" class="form-control" placeholder="Province" required>
      </div>
    </div>

    <div class="mb-3">
      <select class="form-select" name="country" required>
        <option selected>Country</option>
        <option>Sweden</option>
        <option>Denmark</option>
        <option>Denmark</option>
      </select>
    </div>

    <div class="form-check mb-4">
      <input type="hidden" name="save_info" value="off">
      <input class="form-check-input" name="save_info" type="checkbox" id="save-info">
      <label class="form-check-label" for="save-info">Save this information.</label>
    </div>

    <div class="btn-custom">
      <a href="{% url 'core_app:cart' %}" class="btn-outline-secondary">Back to Cart</a>
      <button type="submit" class="btn btn-primary">Go to Shipping</button>
    </div>
  </form>
</div>

{% endblock %}

templates/core_app/checkout/payment.html
{% extends "core_app/checkout/base.html" %}
{% load static %}
{% block body_block %}


<div>
    <ul class="steps">
        <li class="completed">Cart</li>
        <li>></li>
        <li class="completed">Details</li>
        <li>></li>
        <li class="completed">Shipping</li>
        <li>></li>
        <li class="active">Payments</li>
    </ul>

    <form method="post" action="{% url 'core_app:checkout_payment' %}">
        {% csrf_token %}

        <div class="section-heading">
            <h5>Payment method</h5>
        </div>

        <div class="mb-3 border border-dark rounded shadow-sm">
            <div class="credit-card-header text-success d-flex align-items-center gap-2 p-3">
                <span class="material-symbols-outlined" style="font-size: 24px;">
                    credit_card
                </span>
                <h5 class="mb-0">Credit Card</h5>
            </div>

            <div class="p-3">
                <div class="mb-3">
                    <input type="text" name="card_number" class="form-control" placeholder="Card Number">
                </div>
                <div class="mb-3">
                    <input type="text" name="holder_name" class="form-control" placeholder="Holder Name">
                </div>
                <div class="row g-2">
                    <div class="col">
                        <input type="text" name="expiration_date" class="form-control" placeholder="Expiration (MM/YY)">
                    </div>
                    <div class="col">
                        <input type="text" name="cvv" class="form-control" placeholder="CVV">
                    </div>
                </div>
            </div>
        </div>

        <div class="section-heading">
            <h5>Tax Informations</h5>
        </div>

        <div class="mb-3">
            <input type="text" name="vat_number" class="form-control" placeholder="Vat Number (optional)">
        </div>
        <div class="mb-3">
            <input type="text" name="pec" class="form-control" placeholder="PEC (Optional)">
        </div>

        <div class="btn-custom">
            <a href="{% url 'core_app:checkout_shipping' %}" class="btn-outline-secondary text-success">Back to
                shipping</a>
            <button type="submit" class="btn btn-success">Pay now</button>
        </div>
    </form>
</div>

{% endblock %}

templates/core_app/checkout/payment_confirmation.html
{% extends "core_app/checkout/base.html" %}
{% load static %}
{% block body_block %}

<div class="container mt-5 text-center">

  <ul class="steps mb-4">
    <li class="completed">Cart</li>
    <li>></li>
    <li class="completed">Details</li>
    <li>></li>
    <li class="completed">Shipping</li>
    <li>></li>
    <li class="completed">Payments</li>
  </ul>

  <div class="mb-4">
    <i class="bi bi-check-circle" style="font-size: 4rem; color: #28a745;"></i>
  </div>

  <h2 class="mb-4">Payment Confirmed</h2>

  <p class="mb-4"><strong>ORDER no.</strong> {{ order_id }}</p>

  <p class="lead">
    Thank you {{ user.username }} for shopping at <span class="stick-no-bills-font">Candles</span>. The nature is
    grateful to you. Now that your order is confirmed,
    it will be ready to ship in 2 days. Please check your inbox in the future for your order updates.
  </p>

  <div class="btn-custom mt-4">
    <a href="{% url 'core_app:discovery' %}" class="btn btn-outline-secondary">Back to Shopping</a>
    <a href="#" class="btn btn-primary">Print Receipt</a>
  </div>
</div>

{% endblock %}

templates/core_app/checkout/shipping.html
{% extends "core_app/checkout/base.html" %}
{% load static %}
{% block body_block %}


<div>
    <ul class="steps">
        <li class="completed">Cart</li>
        <li>></li>
        <li class="completed">Details</li>
        <li>></li>
        <li class="active">Shipping</li>
        <li>></li>
        <li class="upcoming">Payments</li>
    </ul>

    <form method="post" action="{% url 'core_app:checkout_shipping' %}">
        {% csrf_token %}

        <div class="section-heading">
            <h5>Payment method</h5>
        </div>

        <div class="mb-3 border border-dark rounded shadow-sm">
            <div class="p-3">
                <div class="d-flex col mb-3">
                    <p class="m-2" style="width: 50px;">Contact</p>
                    <input value="{{ contact }}" type=" text" name="contact" class="form-control" placeholder="Contact">
                </div>
                <div class="d-flex col mb-3">
                    <p class="m-2" style="width: 50px;">Ship to</p>
                    <input value="{{ ship_to }}" type="text" name="ship_to" class="form-control" placeholder="Ship to">
                </div>
            </div>
        </div>

        <div class="section-heading">
            <h5>Shipping method</h5>
        </div>

        <div class="mb-3 border border-dark rounded shadow-sm d-flex justify-content-between align-items-center">
            <div class="d-flex align-items-center">
                <input type="radio" name="standard_shipping" class="form-check-input m-4" id="standard_shipping">
                <label class="form-check-label m-0" for="standard_shipping">Standard Shipping</label>
            </div>
            <span class="text-success me-3">Free</span>
        </div>


        <div class="btn-custom">
            <a href="{% url 'core_app:checkout_shipping' %}" class="btn-outline-secondary text-success">Back to
                details</a>
            <button type="submit" class="btn btn-success">Go to payment</button>
        </div>
    </form>
</div>

{% endblock %}